Repository orm-Janggo/flutter_project_orm_Janggo, pull requests merged in 2024-05, with the labels that each got.

#72 59 modifymain screen
  lib/go_router/go_router.dart
  lib/presentation/loading_screen.dart
  lib/presentation/main_screen.dart
  lib/presentation/recipe_screen.dart
Labels: chore

#82 78 fixrecipe image bug appbar bug fix
  assets/images/google_sign_in.png
  lib/data/gpt_data_source/gpt_data_source.dart
  lib/data/gpt_data_source/requestData.dart
  lib/presentation/recipe_screen.dart
  lib/presentation/recipe_view_model.dart
Labels: bug, fix

#91 89 refactoryrecipe main screen UI refactoring
  lib/data/gpt_data_source/gpt_data_source.dart
  lib/data/gpt_data_source/request_data.dart
  lib/main.dart
  lib/presentation/main_screen.dart
  lib/presentation/recipe_screen.dart
Labels: refactory

#96 86 featurerecipe history screen
  lib/go_router/go_router.dart
  lib/presentation/locker/recipe_history/recipe_history_screen.dart
  lib/presentation/recipe_screen.dart
Labels: feature, chore

#98 92 featurelike recipe screen add
  assets/images/heart.png
  lib/presentation/components/like_widget.dart
  lib/presentation/like_recipe_screen.dart
Labels: feature

#109 102 featuregoogle sign in user information handling
  lib/data/repository/chat_gpt_repository_impl.dart
  lib/data/user_information/user_information.dart
  lib/domain/model/social_login/kakao_login.dart
  lib/domain/use_case/get_recipe_use_case.dart
  lib/go_router/go_router.dart
  lib/presentation/kakao_login/kakao_login_ver2.dart
  lib/presentation/main/main_screen.dart
  lib/presentation/main/main_screen_view_model.dart
  lib/presentation/sign/sign_in/google/google_sign_in.dart
  lib/presentation/sign/sign_in/sign_in_screen.dart
  lib/presentation/sign/sign_in/sign_in_view_model.dart
  lib/presentation/sign/sign_up/sign_up_screen.dart
  lib/presentation/splash/splash_screen.dart
  test/data/data_source/picture_data_source_test.dart
Labels: feature, modify

#111 110 fixmypage move bug fix
  lib/presentation/main/main_screen.dart
  lib/presentation/my_page/my_page_screen.dart
Labels: bug, fix

#113 112 fixsign in screen fix
  assets/images/google.png
  assets/images/google_sign_in.png
  lib/presentation/sign/sign_in/google/google_sign_in.dart
  lib/presentation/sign/sign_in/sign_in_screen.dart
Labels: chore

#115 114 featureopen source lisence qa add 1
  lib/go_router/go_router.dart
  lib/main.dart
  lib/presentation/my_page/app_information/app_information_screen.dart
  lib/presentation/my_page/app_information/privacy_policy_screen.dart
  lib/presentation/my_page/app_information/question_answer_screen.dart
  lib/presentation/my_page/my_page_screen.dart
Labels: feature

#128 127 fixlike recipe hive bug fix
  lib/data/db/history/history_recipe_data.dart
  lib/data/db/history/history_recipe_data.g.dart
  lib/data/db/like_hive/like_item.dart
  lib/data/repository/like_recipe_repository_impl.dart
  lib/main.dart
  lib/presentation/locker/recipe_like/like_recipe_screen.dart
  lib/presentation/recipe_screen.dart
  lib/presentation/recipe_screen/recipe_screen.dart
  lib/presentation/recipe_screen/recipe_view_model.dart
  lib/presentation/recipe_view_model.dart
Labels: bug, feature

#129 121 featurehistory recipe detail screen
  lib/go_router/go_router.dart
  lib/presentation/locker/recipe_history/recipe_history_detail/recipe_history_detail_screen.dart
  lib/presentation/locker/recipe_history/recipe_history_detail/recipe_history_detail_state.dart
  lib/presentation/locker/recipe_history/recipe_history_detail/recipe_history_detail_view_model.dart
  lib/presentation/locker/recipe_history/recipe_history_screen.dart
  lib/presentation/locker/recipe_history/recipe_history_view_model.dart
  lib/presentation/recipe_screen/recipe_view_model.dart
Labels: feature, fix

#130 127 fixlike recipe hive bug fix
  lib/data/db/like_hive/like_adapter.dart
  lib/data/db/like_hive/like_item.dart
  lib/data/db/like_hive/like_item.g.dart
  lib/data/repository/like_recipe_repository_impl.dart
  lib/domain/use_case/like_recipe_use_case/like_add_recipe_use_case.dart
  lib/go_router/go_router.dart
  lib/presentation/components/like_widget.dart
  lib/presentation/locker/recipe_like/like_recipe_screen.dart
  lib/presentation/recipe_screen/recipe_screen.dart
  lib/presentation/recipe_screen/recipe_state.dart
  lib/presentation/recipe_screen/recipe_state.freezed.dart
  lib/presentation/recipe_screen/recipe_state.g.dart
  lib/presentation/recipe_screen/recipe_view_model.dart
Labels: bug, chore, fix

#133 131 featurelike recipe screen correction
  assets/images/x.png
  lib/data/db/like_hive/like_adapter.dart
  lib/data/db/like_hive/like_item.dart
  lib/data/db/like_hive/like_item.g.dart
  lib/go_router/go_router.dart
  lib/presentation/components/like_widget.dart
  lib/presentation/locker/recipe_like/like_recipe_screen.dart
  lib/presentation/recipe_screen/recipe_screen.dart
  lib/presentation/recipe_screen/recipe_view_model.dart
  pubspec.lock
  pubspec.yaml
Labels: modify

#135 134 fixnon login guest fix
  lib/presentation/recipe_screen/recipe_view_model.dart
  lib/presentation/splash/splash_screen.dart
Labels: fix

#152 140 featurelike recipe detail screen add
  lib/go_router/go_router.dart
  lib/presentation/components/like_widget.dart
  lib/presentation/locker/recipe_history/recipe_history_detail/recipe_history_detail_screen.dart
  lib/presentation/locker/recipe_history/recipe_history_detail/recipe_history_detail_view_model.dart
  lib/presentation/locker/recipe_like/like_recipe_detail_screen.dart
  lib/presentation/locker/recipe_like/like_recipe_screen.dart
  lib/presentation/locker/recipe_like/like_recipe_viewmodel.dart
Labels: bug, feature

#155 154 fixgo router bug fix
  lib/go_router/go_router.dart
  lib/presentation/components/like_widget.dart
  lib/presentation/locker/recipe_history/recipe_history_screen.dart
  lib/presentation/recipe_screen/recipe_screen.dart
Labels: fix

#157 [ADD] like_recipe_detail_screen.dart add
  lib/presentation/locker/recipe_like/like_recipe_detail_screen.dart
Labels: feature

#165 [FIX] second refactoring
  analysis_options.yaml
  lib/data/data_source/gpt_data_source/gpt_data_source.dart
  lib/data/data_source/gpt_data_source/request_data.dart
  lib/data/db/like_hive/like_item.dart
  lib/data/mapper/like_recipe_mapper.dart
  lib/data/repository/like_recipe_repository_impl.dart
  lib/data/repository/recipe_repository_impl.dart
  lib/domain/model/like_model.dart
  lib/domain/repository/chat_gpt_repository.dart
  lib/domain/repository/like_recipe_repository.dart
  lib/domain/use_case/get_food_name_use_case.dart
  lib/domain/use_case/get_recipe_use_case.dart
  lib/domain/use_case/like_recipe_use_case/like_add_recipe_use_case.dart
  lib/presentation/locker/recipe_like/like_recipe_detail_screen.dart
  lib/presentation/locker/recipe_like/like_recipe_screen.dart
  lib/presentation/locker/recipe_like/like_recipe_viewmodel.dart
  lib/presentation/recipe_screen/recipe_view_model.dart
  lib/router/go_router.dart
  test/data/data_source/picture_data_source_test.dart
Labels: chore

#172 170 fix get it error fix
  lib/data/data_source/gpt_data_source/request_data.dart
  lib/di/di_setup.dart
Labels: fix

#174 169 fixrecipe data source fix
  lib/domain/use_case/recipe_use_case/get_food_name_use_case.dart
  lib/presentation/recipe_screen/recipe_view_model.dart
Labels: fix
