Repository orm-Janggo/flutter_project_orm_Janggo, pull requests merged in 2024-04, with the labels that each got.

#12 [FIX] gpt_data_source, pubspec.yaml fix
  .gitignore
  android/app/build.gradle
  lib/core/confige/chat_gpt_configue.dart
  lib/data/gpt_data_source/gpt_data_source.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
  test/gpt_test.dart
Labels: feature, chore, fix

#15 4 featureingrediant model
  .gitignore
  lib/core/config/api_config.dart
  lib/data/data_source/picture_data_source.dart
  lib/data/dto/picture_dto.dart
  lib/data/gpt_data_source/gpt_data_source.dart
  lib/data/mapper/picture_mapper.dart
  lib/data/repository/picture_repository_impl.dart
  lib/data/repository/repository_impl.dart
  lib/domain/model/picture_model.dart
  lib/domain/model/picture_model.freezed.dart
  lib/domain/model/picture_model.g.dart
  lib/domain/repository/picture_repository.dart
  pubspec.lock
  pubspec.yaml
  test/gpt_test.dart
Labels: feature, fix, modify

#16 14 fix chat gpt api fix detail
  .gitignore
  lib/data/gpt_data_source/gpt_data_source.dart
  pubspec.lock
  pubspec.yaml
  test/gpt_test.dart
Labels: feature

#17 [MODIFY] pubspec.yaml fix final
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/janggo/MainActivity.kt
  assets/images/image.dart
  pubspec.yaml
Labels: fix

#20 6 featurekakao login
  android/.gitignore
  android/app/build.gradle
  android/app/google-services.json
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/orm/janggo/MainActivity.kt
  assets/images/janggo_main.json
  assets/images/janggo_main2.json
  assets/images/kakao_login_button.png
  lib/main.dart
  lib/presentation/kakao_login/kakao_login.dart
  lib/presentation/kakao_login/kakao_login_ver2.dart
  lib/presentation/kakao_login/loginViewModel.dart
  lib/presentation/kakao_login/social_login.dart
  lib/presentation/login_screen.dart
  lib/presentation/login_screen_ver2.dart
Labels: feature, chore

#23 19 featureingredient screen add
  lib/data/gpt_data_source/gpt_data_source.dart
  lib/data/repository/chat_gpt_reopository_impl.dart
  lib/domain/repository/chat_gpt_repository.dart
  lib/main.dart
  lib/presentation/main_screen.dart
Labels: feature

#25 18 featureadd recipe detail screen
  lib/data/data_source/picture_data_source.dart
  lib/data/repository/picture_repository_impl.dart
  lib/domain/repository/picture_repository.dart
  lib/domain/use_case/get_picture_use_case.dart
  lib/presentation/recipe_screen.dart
  lib/presentation/recipe_view_model.dart
  pubspec.lock
  test/data/data_source/picture_data_source_test.dart
Labels: feature

#44 [ADD] recipe text success
  lib/data/gpt_data_source/gpt_data_source.dart
  lib/data/repository/chat_gpt_reopository_impl.dart
  lib/domain/use_case/get_picture_use_case.dart
  lib/domain/use_case/get_recipe_use_case.dart
  lib/go_router/go_router.dart
  lib/presentation/main_screen.dart
  lib/presentation/recipe_screen.dart
  lib/presentation/recipe_state.dart
  lib/presentation/recipe_state.freezed.dart
  lib/presentation/recipe_state.g.dart
  lib/presentation/recipe_view_model.dart
Labels: feature

#46 [FIX] main screen ui fix
  lib/presentation/main_screen.dart
Labels: feature

#45 [ADD] mypage screen 생성
  lib/presentation/mypage_screen.dart
Labels: feature

#49 43 featuresplash screen
  assets/images/home_background.png
  assets/images/image.dart
  assets/images/janggo_main2.json
  assets/images/kakao_login_large_wide.png
  assets/images/main_background.png
  firepit-log.txt
  lib/data/gpt_data_source/gpt_data_source.dart
  lib/data/repository/chat_gpt_reopository_impl.dart
  lib/domain/use_case/get_picture_use_case.dart
  lib/domain/use_case/get_recipe_use_case.dart
  lib/go_router/go_router.dart
  lib/main.dart
  lib/presentation/home_screen.dart
  lib/presentation/kakao_login/kakao_login_ver2.dart
  lib/presentation/login_screen.dart
  lib/presentation/main_screen.dart
  lib/presentation/recipe_screen.dart
  lib/presentation/recipe_state.dart
  lib/presentation/recipe_state.freezed.dart
  lib/presentation/recipe_state.g.dart
  lib/presentation/recipe_view_model.dart
Labels: feature

#54 47 featureadd new sign up
  lib/presentation/mypage_screen.dart
  lib/presentation/sign_up_ui_screen.dart
Labels: feature, modify

#61 56 modifychange recipe screen
  lib/presentation/recipe_screen.dart
Labels: feature

#65 59 modifymain screen
  assets/images/book.gif
  assets/images/empty_image.png
  assets/images/main-background.png
  assets/images/main_background.png
  assets/images/기본이미지.png
  devtools_options.yaml
  lib/presentation/home_screen.dart
  lib/presentation/loading_screen.dart
  lib/presentation/main_screen.dart
  lib/presentation/recipe_screen.dart
  lib/presentation/splash_screen.dart
Labels: feature, chore, modify
